name: careerplanner
description: Career Planner App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by lots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_analytics: ^6.0.2
  firebase_core: ^0.5.0+1
  firebase_crashlytics: ^0.2.1+1
  firebase_messaging: ^7.0.3
  firebase_auth: ^0.18.1+2
  firebase_database: ^4.1.1
  cloud_firestore: ^0.14.1+3
  firebase_dynamic_links: ^0.6.0+2
  flutter_sentry: ^0.4.4
  flutter_secure_storage: ^3.3.5
  country_code_picker: ^1.6.0
  pin_view: ^1.0.1
  rxdart: ^0.24.1
  sentry: any
  animate_do: ^1.7.3
  google_nav_bar: ^3.1.0
  webview_flutter: ^1.0.3
  carousel_slider: ^2.3.1
  google_fonts: ^1.1.1
  liquid_pull_to_refresh: ^2.0.0
  cached_network_image: ^2.3.3
  flutter_cache_manager: ^2.0.0
  tutorial_coach_mark: ^0.5.1
  shared_preferences: ^0.5.12+2
  introduction_screen: ^1.0.9
  search_page: ^1.3.0
  animations: ^1.1.2
  flutter_rating_bar: ^3.0.1+1
  flutter_gradient_colors: ^1.0.0
  tinycolor: ^1.0.3
  transparent_image: any
  auto_animated: any



dev_dependencies:
  flutter_launcher_icons: ^0.8.0
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/illustrations/hugo-uploading.png
    - assets/icon/CAREER_PLANNER_FOREGROUND.png
    - assets/icon/CAREER_PLANNER_FOREGROUND_SMALL.png
    - assets/illustrations/hugo-list-is-empty.png
    - assets/illustrations/flame-training.png
    - assets/illustrations/kingdom-4.png
    - assets/illustrations/friendship.png
    - assets/illustrations/eastwood-school-bag.png
    - assets/illustrations/bermuda-704.png
    - assets/illustrations/bermuda-classroom.png
    - assets/illustrations/bermuda-765.png
    - assets/illustrations/bermuda-school.png
    - assets/illustrations/bermuda-page-not-found.png
    - assets/illustrations/bermuda-759.png
    - assets/illustrations/bermuda-699.png
    - assets/illustrations/sign-in-4.png
    - assets/illustrations/clip-1063.png
    - assets/illustrations/hugo-page-not-found.png
    - assets/illustrations/4086124.png
    - assets/icon/ICON_CIRCLE.png
    - assets/illustrations/hugo-productive-work.png
    - assets/illustrations/robots.png
    - assets/illustrations/hugo-co-workers.png
    - assets/illustrations/hugo-success-1.png
    - assets/illustrations/clip-woman-resting-on-nature-1.png
    - assets/illustrations/clip-business-start-up-concept.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon/CAREER_PLANNER_ICON.png"
  image_path_android: "assets/icon/CAREER_PLANNER_ICON.png"
  adaptive_icon_background: "assets/icon/CAREER_PLANNER_BACKGROUND.png"
  adaptive_icon_foreground: "assets/icon/CAREER_PLANNER_FOREGROUND.png"

flutter_native_splash:
  image: assets/icon/CAREER_PLANNER_FOREGROUND.png
  color: "421872"
  fill: true